### ISSUE TITLE
Runtime Exception on startup.

### ISSUE THREAD

**Issue by Aquaeyes** [RealRTTV/malum-quilt#17]
[latest.log](https://github.com/RealRTTV/malum-quilt/files/9070489/latest.log)

> RuntimeException: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
> NoClassDefFoundError: com/llamalad7/mixinextras/MixinExtrasBootstrap
> ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap

Mod versions:

malum-quilt-b1.1.2
qfapi-2.0.0-beta.4_qsl-2.0.0-beta.10_fapi-0.57.0_mc-1.19
trinkets-3.4.0
and using quilt loader 0.17.1-beta.6-1.19

**Comment by Aquaeyes** [comment]
Now I'm getting `Critical injection failure: @ModifyVariable annotation on malum$brilliantObeliskEnchantmentPower could not find any targets matching 'm_mpsetdhw' in net.minecraft.class_1718`?
[latest.log](https://github.com/RealRTTV/malum-quilt/files/9070655/latest.log)

**Comment by Arathain** [comment]
@Aquaeyes should work now - download latest on either platform & it should run fine

**Comment by Aquaeyes** [comment]
Works like a charm! Only issue is that modrinth doesn't seem to have the new file? The one on curseforge works wonderfully though, tyvm!

**Comment by Arathain** [comment]
modrinth does have the new file, I modified the b1.1.3 version directly instead of uploading a new one

**Comment by Aquaeyes** [comment]
Modrinth's download shows as 9259KB, the same as the prior version, and also gives the same crash, with curseforge being 9260KB. Unless some weird caching is going on, in which case, heck.
