### ISSUE TITLE
Injection error crash

### ISSUE THREAD

**Issue by Sunconure11** [RealRTTV/malum-quilt#22]
https://pastebin.com/AwtMBURT

**Comment by Sunconure11** [comment]
This is because of an issue with Soul Fire'd. 

https://www.curseforge.com/minecraft/mc-mods/soul-fired

@nyphet

**Comment by Nyphet** [comment]
Hi, I'm quite new to mixins, how did you determine the injector conflict was because of Soul Fire'd?  
Anyway it does make sense as I indeed inject at that point of code with `@Redirect` annotation.  
Unfortunately, no idea on how to fix this on my side at the moment.

**Comment by Sunconure11** [comment]
Both of you are using `getFireAspect` in some way.

**Comment by Sunconure11** [comment]
And in your case @Nyphet, it seems you are altering it in such a way that causes conflicts with the two mods.

**Comment by Nyphet** [comment]
I believe the crash is happening because Redirect and ModifyVariable injectors refer to the same target, mine just happens to be applied after and overrides Malum's one.  
The same problem would happen if my injector was applied first and Malum's one was applied after, it just depends on the loading order.  
I'm looking for a solution that chains injectors rather than overriding them, but I'm not sure that it's applicable for this case.

**Comment by Nyphet** [comment]
I may have found a solution on my side, would you be available to test it out if I attached here the jar?

**Comment by Sunconure11** [comment]
I should be able

**Comment by Nyphet** [comment]
[soulfired-1.19.2-1.1.0.0-fabric.zip](https://github.com/RealRTTV/malum-quilt/files/9636857/soulfired-1.19.2-1.1.0.0-fabric.zip)
Try out this version and let me know if it still crashes and whether it works or not, thank you (you need to unzip it to get the jar)

**Comment by Nyphet** [comment]
Great! Then by the end of this week I will release the new version, thank you for reporting the issue and testing the solution!  
You can close the issue now

**Comment by Sunconure11** [comment]
@Nyphet Error returned with the new Curse build.

**Comment by Nyphet** [comment]
The same exact error? That is weird, I uploaded on Curseforge the same jar I attached here.
Can you show again the logs?

**Comment by Sunconure11** [comment]
The launcher is not picking up on the version.

**Comment by Nyphet** [comment]
I just checked and versions for 1.19.1 and 1.19.2 are still under review. It may need some time before they become available, I don't have any control on that as it solely depends on the Curseforge team.
